# Generated by Django 5.0.14 on 2025-08-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('total_words', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Main URL',
                'verbose_name_plural': 'Main URLs',
                'db_table': 'main_url',
            },
        ),
        migrations.CreateModel(
            name='SubURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_url', models.URLField(max_length=500)),
                ('words', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_urls', to='scraper.mainurl')),
            ],
            options={
                'verbose_name': 'Sub URL',
                'verbose_name_plural': 'Sub URLs',
                'db_table': 'sub_url',
                'unique_together': {('main_url', 'sub_url')},
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_tag', models.CharField(blank=True, max_length=10, null=True)),
                ('content', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_contents', to='scraper.suburl')),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
                'db_table': 'page_content',
            },
        ),
    ]
