# Generated by Django 5.0.14 on 2025-08-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scrapedurl_crawlsession_enhancedmainurl_and_more'),
    ]

    operations = [
    ]
