# Generated by Django 5.0.14 on 2025-08-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20250823_2345'),
    ]

    operations = [
    ]
