# Generated by Django 5.0.14 on 2025-08-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_create_enhanced_models'),
    ]

    operations = [
    ]
