# Generated by Django 5.0.14 on 2025-08-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_create_models'),
    ]

    operations = [
    ]
