# Generated by Django 5.0.14 on 2025-08-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_create_initial_models'),
    ]

    operations = [
    ]
